### PR TITLE
Add postgres 14 binaries

### PR DESCRIPTION
**Pull request by NanoCode012**
Version: Postgres 14.5
Node 14.x
Arch: x86_64
Issue: https://github.com/jameshy/pgdump-aws-lambda/issues/28#issuecomment-1254735916

Created using Amazon EC2 AWI 2

### CODE REVIEW

**Comment by NanoCode012** [comment]
Hey, @jameshy , would it be possible to get this checked out/merged? If there's any issue that I can help with, feel free to tell me.

**Comment by jameshy** [comment]
Hi @NanoCode012 . My apologies for the delay!

Could you please chmod the binaries so they are executable?

**Comment by NanoCode012** [comment]
> Hi @NanoCode012 . My apologies for the delay!
> 
> Could you please chmod the binaries so they are executable?
> 
> .. so `chmod +x`

Hi @jameshy , I have added 774 to the `pg_dump` binary. I didn't chmod the `.so` files like the other folders. Is this fine?

I have also updated this branch, so that it won't conflict with base.

**Comment by jameshy** [comment]
Yep i think it's okay, i will test while building a new release.

Many thanks for your contribution!

**Pull request merged**
